/* ============================================================
   columns.js — original opinion columns (programme.html only).
   Split out of app.js because this grows indefinitely (the
   scheduled routine adds one roughly weekly) while every other page
   pays app.js's byte cost on every load; programme.html is the only
   page that needs this data.
   Loaded by programme.html via <script src="columns.js"></script>,
   right before its own inline render script.
   ============================================================ */
/* ============================================================
   COLUMNS — original opinion writing, in the site's own voice.
   Newest first. Grows over time (the scheduled routine adds one
   roughly weekly once the last entry is stale) rather than sitting
   at a fixed three forever — programme.html just renders whatever's
   here, it never carries its own hardcoded essays.
   ============================================================ */
const COLUMNS = [
  {date:'2026-09-22', title:'The break nobody in Brisbane asked for', byline:'On the interlull, and getting your Saturdays back',
   standfirst:'Two and a half weeks with nothing to set an alarm for. This is meant to feel like relief.', paras:[
    'The last thing on my phone before I put it face-down and went to bed on Saturday night was the final whistle notification from the Amex. The first thing on it Sunday morning was a WhatsApp from the same Malaysian group chat that lost its mind over Ødegaard in Naples, and this time nobody was typing anything, which somehow said more than any of them typing something would have.',
    'Then Monday arrived and there was no fixture to check. Nor Tuesday. The next Arsenal match is the tenth of October, which means for the first time since the middle of August there is no 1am, no 4am, no set of numbers on this site telling me whether a kick-off falls inside the brutal window. For three weeks the brutal window does not exist, because there is nothing to be brutal about.',
    'I want to report that this feels like relief and it mostly does not. It feels like being sent to your room to think about what you did, except what you did was watch, and there is nothing to think about that hasn’t already been said better by Arteta himself, standing in front of a Sky Sports backdrop saying the team didn’t respect the basics. He is not wrong and repeating it for seventeen days does not make it more useful.',
    'What the interlull is actually for, if you strip the sentiment out of it, is time. Time for a treatment room that has not been empty since pre-season to actually empty out. Time for Bruno Guimarães to train with these players every day for a fortnight instead of being introduced to them at Premier League speed on a Friday night in Sussex. Time, frankly, for the rest of us to stop refreshing a table that currently has us second on goal difference and remember that it is the twenty-second of September.',
    'World Cup qualifiers will fill some of the gap for the players who are away with their countries, which is its own kind of small mercy — competitive minutes without the specific weight of the shirt that got dismantled on Saturday. For the rest of us there is nothing scheduled, which is either the healthiest thing that could happen to this squad right now or a very long three weeks to sit with 0–3, depending on the day you ask me.',
    'Set your alarm for October the tenth anyway. Old habits.'
  ]},
  {date:'2026-09-22', title:'What the treatment room actually needed', byline:'On the international break, medically speaking',
   paras:[
    'Strip away the table and the result and look at what this squad has actually been carrying into the last three matchweeks. Ben White withdrawn at Sunderland with what looked like a groin complaint before half-time. William Saliba missing the Ipswich Carabao Cup tie with a back problem picked up in the same week. Cristhian Mosquera a doubt of his own. Jurrien Timber only just back from his own spell out, thrown a half at Sunderland to prove he could take it, and by all accounts coming through clean.',
    'That is not a back four. That is a rotation of whoever was standing up on the day, and it has been that way since before the Brighton performance that everyone is currently, correctly, furious about. Nobody excuses a 0–3 with an injury list — Brighton would have won that on a full-strength day too, on the balance of the first half hour — but it is worth saying plainly that this was never the back line Arteta drew up in pre-season, and it has not been for a month.',
    'Eighteen days without a competitive fixture is not a small thing for a defence that has been held together with fitness-test optimism since the second week of September. White gets a real block of rest instead of a between-matches taping job. Saliba gets the same. Whatever Mosquera’s issue actually is gets time to resolve itself properly instead of being managed around a Saturday.',
    'The version of Arsenal that plays Leeds on the tenth of October should, in theory, have more of its actual first-choice back four available than the version that lined up at the Amex. Whether they play any better than that version is an entirely separate question, and one the break can’t answer for them. It can only clear the runway.'
  ]},
  {date:'2026-09-21', title:'Four wins, then the version of Arsenal we were chasing off', byline:'On matchday five, and the record that got away',
   paras:[
    'Eight straight wins to open a season is a club record that has stood since 1903–04, which is a fact I did not know until this week and now cannot stop thinking about, because Arsenal were four results into a genuine attempt at it and nobody outside the football press had really clocked it was happening. Coventry, Aston Villa, Chelsea, Sunderland — four wins from four, the reigning champions doing exactly what reigning champions are supposed to do to the sides underneath them, and the record sitting there quietly at the edge of the conversation waiting for matchday five to either confirm it or kill it.',
    'Brighton killed it, comprehensively, and I think the record chase is actually the more useful way to think about Saturday than the raw scoreline is. 0–3 away from home is a bad result on its own terms. 0–3 away from home on the exact afternoon a 123-year-old record was within reach is a result with a shape to it, and the shape is this: this group is still learning what it means to be hunted rather than hunting.',
    'That sentence isn’t new — it was more or less the whole argument of the season-opener column a month ago, back when “the squad is better than the one that won it” felt like the only thing worth saying. Chasing is easy. Being chased is the test. Four flawless weeks made that line sound like a formality. One afternoon at the Amex, with Brighton first to every second ball and Arsenal unable to solve a single problem in transition, turned it back into the actual question of the season.',
    'None of which means panic. A club that has just won its first title in twenty-two years does not lose its nerve over one Saturday, and the table — second, on goal difference, five games in — says this is a bad afternoon and not yet a crisis. But the record is gone, and it was never really about the record. It was a convenient way of noticing, early, whether this group had actually changed the way it carries pressure. Saturday gave us the answer we didn’t want. Better to get it in September than in April.'
  ]},
  {date:'2026-09-20', title:'The Amex has never needed a script', byline:'On Brighton 3-0 Arsenal',
   paras:[
    'Seven minutes in, Bruno Guimarães, on his full Premier League debut for this club, gave the ball away in a area of the pitch where giving the ball away means something. It was a small moment and it did not decide anything on its own, but it set a tone that Arsenal spent the rest of the afternoon failing to shake, on a ground that has made a house style out of punishing exactly that kind of hesitation.',
    'Pascal Gross made it count in the thirty-first minute, a clean strike from twenty yards that went in off David Raya’s near post — the sort of finish that looks soft in isolation and inevitable once you’ve watched the buildup to it. Charalambos Kostoulas doubled it right on the stroke of half-time with a low, unstoppable strike from twenty-two yards, the kind of goal that turns a bad half into a genuinely alarming one. Chema Andrés made it three seven minutes into the second, unmarked at a corner, which is the detail that will annoy Arteta longest, because unmarked at a corner is a solved problem in professional football and Saturday it wasn’t solved.',
    'Bukayo Saka, by most readings of the afternoon including the club’s own, was largely anonymous — a sentence that would have seemed unthinkable in August and is worth sitting with rather than explaining away. Kai Havertz had the best of Arsenal’s scraps late on and didn’t take it. There is no passage of this game that reads as bad luck. Brighton were first to the second ball all afternoon, and a team that is first to the second ball all afternoon usually wins by exactly this margin.',
    '“Extremely disappointed,” Arteta said afterwards, and to his credit led with Brighton rather than his own side: “I think they deserve it, I think they were the better team.” That is the correct order to say those two things in, and it is also, underneath the good manners of it, as honest an assessment as you’ll get from a manager forty minutes removed from watching his champions dismantled.',
    'This site has spent five weeks writing about a team that looked finished with the business of proving things to anyone. Saturday was a reminder that the proving never actually stops, it just changes shape. Nobody enjoyed watching it arrive at four in the morning. Nobody’s pretending otherwise here either.'
  ]},
  {date:'2026-09-20', title:'One bad Saturday for £75m', byline:'On Bruno Guimarães, and patience',
   paras:[
    'The easiest sentence to write after Brighton is the one blaming the new signing, and I’m not going to write it, so let’s deal with what actually happened instead. Seven minutes into his first Premier League start for this club, Bruno Guimarães gave the ball away in his own half. It was a bad touch under early pressure from a player who had trained with these teammates for barely a month, in a stadium that specialises in making exactly that kind of touch look worse than it is. It was not, on its own, a three-goal problem.',
    'This is the part of a big transfer nobody enjoys and everybody has to live through anyway — the gap between a player’s reputation and the specific timing of the passes around him. Guimarães spent four years being one of the most complete midfielders outside the traditional big six, reading games at a tempo most of the league can’t match. None of that transfers instantly. It transfers over months, in training sessions and half-time tactical notes and the hundred small non-verbal agreements a midfield develops about who covers what when the ball is lost.',
    'The interlull, awkwardly, is probably the single best thing that could happen to him right now. Two weeks of Arsenal training rather than Arsenal matches. Time to build the relationship with Rice and Ødegaard that Saturday exposed as still under construction, away from the pressure of a Saturday 3pm and a stadium that had already decided what kind of afternoon it wanted.',
    'Seventy-five million pounds buys a player, not a finished partnership. Judge him again in November, not off one bad Saturday at the Amex — and if he’s still making that pass in November, this column will say so.'
  ]},
  {date:'2026-09-11', title:'The armband is not vacant', byline:'On Ødegaard, after Naples',
   standfirst:'Twenty-six shots in Naples, and the only one that mattered belonged to the man half of you spent the summer trying to demote.', paras:[
    'Late on, with the game finally cracking a little, Kevin De Bruyne was played through. Clean. The one moment Napoli had been permitted all evening, handed to the one player in their side capable of doing something irreversible with it. He chose to cross.',
    'Arsenal’s version of that moment had already happened, fifteen minutes earlier, and had gone rather differently. Intricate build-up, the ball worked back to the edge of the box, and Martin Ødegaard hit it low and hard enough that it went in off the post. No hesitation in it. No looking for a better option, because there wasn’t one, and he knew it before the ball arrived.',
    'That contrast is the match. Two footballers of genuine quality were each offered a decision, and only one of them took it.',
    'The structural read is less flattering to Arsenal than the scoreline suggests, which is a strange thing to say about a night that produced twenty-six shots and 4.05 expected goals against 0.22. Thirteen of those shots came in the first half, the most Arsenal have managed in the first half of a Champions League away game since records began in 2003-04. In Naples. In heat you could chew. Against a side that had turned up off back-to-back league defeats and set up accordingly.',
    'What that number tells you is that the chance creation is now industrial. It doesn’t require a moment of inspiration or a set-piece lottery ticket or an opposition error. The machine simply runs, and shooting positions come out of the end of it at a rate that would have seemed fanciful eighteen months ago. Arsenal did not need anything unusual to happen in that first half. They needed roughly forty-five more minutes of exactly what they were already doing.',
    'The machine has one part it cannot manufacture, though, and that’s the last decision. Volume is a system property. Finishing is a personal one. And on the evidence of Wednesday, Arsenal currently have precisely one player reliably converting the system’s output into points.',
    'Which brings us to Bukayo Saka, and I’m going to be blunt about it because pretending otherwise helps nobody. Five shots in the first half worth 0.95 xG. That is nearly a full goal’s worth of opportunity, taken and discarded by one man before the interval. Some of that is bad luck and some of it is bad shooting, and the honest position is that we can’t always tell which is which from the sofa. What we can say is that a striker’s evening’s work went unconverted.',
    'The generous framing, which is also the true one, is that getting into those positions five times in forty-five minutes is the harder half of the job. Saka was where he was supposed to be, repeatedly, in a stadium designed to make players stop wanting to be there. Mikel Merino had his own version of it, meeting an Eze header back across goal and finding the keeper’s hands. Neither of them hid. Both of them will have watched it back with a face on.',
    'I watched it at five in the morning in Brisbane with a shift waiting for me, which meant Ødegaard’s goal landed in a room where I couldn’t make any noise, and the only place to put it was a Malaysian WhatsApp group that had been quietly losing its mind for an hour. By the time De Bruyne squared it, I was already thinking about the dispensary. Seventeen years of this and the geography still hasn’t improved.',
    'The thing worth sitting with is the frequency. Ødegaard’s fourth goal in five games this season, and the second winner in five days after he’d already settled the Chelsea game at the weekend. Two matches that were finely balanced and could have gone either way, and both of them were closed by the same player. He also led every player on the pitch in Naples for chances created with six, in touches with 120, and in line-breaking passes with five. He built the thing and then finished it.',
    'There was a fashionable argument this summer that the armband had drifted to the wrong man, that Declan Rice’s presence and volume and force of personality made him the more natural captain, and that Ødegaard’s version of leadership was too quiet to be leadership at all. I understand why people find that argument attractive. Rice is enormously good and enormously visible, and there’s a certain type of supporter who will always mistake noise for authority.',
    'Wednesday was the rebuttal, and it wasn’t even a loud one. Ødegaard’s captaincy shows up in the ninety seconds a game where somebody has to be certain, and everybody else is calculating.',
    'The development angle is the four changes. Arteta rotated four players from the Chelsea win, took that side to Naples on matchday one, and the performance level did not move an inch. Twelve months ago the honest worry about this squad was whether it could survive rotation, whether the fluency was load-bearing on specific individuals, whether the away trips in Europe would go the way European away trips historically go for Arsenal. Five wins from five in all competitions plus the Community Shield, and one defeat in the last twelve European away games, is an answer to a question that used to make me uncomfortable.',
    'It’s also why the miss count matters more than it looks. This team is no longer at risk of losing these games. It is at risk of drawing them, and drawing matchday one in Naples is how you find yourself in a February playoff round explaining that the underlying numbers were fine. 4.05 to 0.22 and a one-goal margin is a result and a warning arriving in the same envelope.',
    'Napoli, for their part, will feel they got away with something. Allegri had them arranged to survive, and they survived for seventy-five minutes, which under the circumstances counts as a plan working right up until it didn’t.',
    'Rice will captain this club, probably for a long time, and he’ll be excellent at it. He can wait his turn. The current holder is busy.'
  ]},
  {date:'2026-09-10', title:'One Napoli night doesn’t make a European campaign', byline:'On matchday 1', paras:[
    'An away win at a ground that eats away form teams alive is a good habit to start the league phase with, and it is worth saying plainly: Ødegaard scoring the winner with fifteen minutes left, off a Tzolis assist, in Naples, is exactly the kind of result that gets forgotten by January and mattered enormously on the night.',
    'What it does not do is tell you anything about matchday 3 at the Allianz. Eight games, four pots, and a format specifically designed so that one bad Tuesday in a random city can undo three good ones. The habit that matters is not winning the big away nights — it is not dropping points at home to the sides you are supposed to beat, because that is where league-phase campaigns actually die.',
    'Enjoy Naples. Then forget about it by Friday.'
  ]},
  {date:'2026-08-21', title:'Defending it is a completely different job', byline:'Season opener · August 2026', paras:[
    'Twenty-two years is a long time to spend explaining to people why the wait was nearly over. Now it is over, and the strange thing nobody warns you about is that winning the thing does not make the next season easier. It makes it louder. Every draw is a wobble. Every substitution is a referendum. Every set-piece conceded gets its own six-minute segment on a channel you have never heard of.',
    'The squad is better than the one that won it. Bruno Guimarães walking into a midfield that already had Zubimendi, Rice and Ødegaard is faintly obscene. Tzolis gives us a left side that does not depend on one man’s hamstring. Hincapié is permanent. Meslier is a free goalkeeper who has played a hundred Premier League games. This is what a club looks like when it has stopped being sentimental about the gaps.',
    'What we are actually watching for this year is whether the standards hold when the motivation changes. Chasing is easy. Being chased is the test.'
  ]},
  {date:'2026-08-15', title:'In defence of the captain, again, forever', byline:'On Martin Ødegaard', paras:[
    'Every eighteen months the discourse cycles back to whether the armband should move. It is always framed as a compliment to Declan Rice, which is a neat trick, because it means anyone defending Ødegaard sounds like they are attacking a player everyone loves.',
    'So let’s be plain about it. Captaincy at this club, under this manager, is not about who wins the most duels. It is about who holds the shape of the idea when the game is going badly — who keeps demanding the ball in the pocket at 0-0 away from home in the 71st minute when the easy thing is to hide. He does that in games where his numbers look ordinary. That is precisely the point.',
    'Also he scored in the opener and the shot took a deflection, which is the most Ødegaard sentence ever written.'
  ]},
  {date:'2026-08-10', title:'A word on watching this from 16,000km away', byline:'The Brisbane clause', paras:[
    'There is a specific kind of supporter who has never once walked up Drayton Park but can tell you exactly what the away kit looked like in 2011 because they were awake at 2am to see it. That is most of us out here. The fixture list is not a fixture list, it is a sleep schedule, and a 3pm Saturday in London is midnight on Sunday morning in Queensland.',
    'So this site puts the Brisbane time next to every kick-off, and flags the ones that land between 1am and 6am — the genuinely brutal ones, where you either commit or you spend Sunday morning dodging the score. Both are respectable choices. Only one of them is correct.'
  ]}
];
