/* ============================================================
   news-data.js — this site's own original news coverage.
   Split out of app.js for the same reason columns.js was: this grows
   indefinitely (the scheduled routine prepends a new item roughly
   every few days) while every page that loads app.js paid its byte
   cost. news.html renders the full list; index.html reads only
   NEWS[0] for the homepage widget teaser.
   Loaded by both pages via <script src="news-data.js"></script>,
   right after app.js.
   ============================================================ */
/* ============================================================
   NEWS — this site's own original coverage. Every entry: a short
   original write-up (never a copied sentence) plus a real, working
   link to the primary source. Newest first — the scheduled routine
   prepends new items here, it never rewrites news.html itself.
   ============================================================ */
const NEWS = [
  {date:'2026-10-02', headline:'Ødegaard gets through the full 90 — the ankle scare is over',
   summary:'Ten days after being kicked from behind by Bernardo Silva and sitting out a Norway training session with a sore ankle, Martin Ødegaard was passed fit to start against Wales in Cardiff on Thursday night and played every one of the ninety minutes. Craig Bellamy’s side won 2-1 with Erling Haaland kept quiet throughout, which from this site’s chair is an entirely acceptable way for the captain’s international break to end. He comes back into a free weekend before Leeds visit the Emirates on the tenth — the fixture every one of these injury updates has really been building towards.',
   source:'Sports Mole', url:'https://www.sportsmole.co.uk/football/arsenal/news/arsenal-handed-major-injury-boost-ahead-of-pl-return_606087.html'},
  {date:'2026-10-01', headline:'Saliba’s rehab finally gets a month attached to it: November',
   summary:'Arseblog News has the first real timeline on William Saliba since the back problem that followed him home from France’s World Cup campaign — a November target. Treat it as a target rather than a promise: surgery was ruled out back in August in favour of a managed rehabilitation programme precisely because backs don’t reward being rushed, and this club has had enough soft-tissue setbacks already this season to know better than to pencil in a fixture. But after weeks of nothing more specific than “no confirmed return date,” a month is still a month.',
   source:'Arseblog News', url:'https://arseblog.news/2026/10/report-saliba-targeting-november-return/'},
  {date:'2026-09-30', headline:'Ødegaard’s ankle is now the one thing Arsenal are watching',
   summary:'Norway’s captain was kicked from behind by Bernardo Silva late in Sunday’s 2-1 defeat to Portugal in Oslo, and by Tuesday he was sitting out training with the ankle still too sore to work on. Nothing has been ruled out: the Norway staff say it is improving day by day and Wales are not until the first of October, with Portugal again on the fourth. What decides the story is the scan, and the reason nobody at Arsenal is relaxed about it is that the last serious ankle injury he picked up in a Norway shirt, in 2024, reportedly cost him twelve Arsenal matches.',
   source:'Sports Mole', url:'https://www.sportsmole.co.uk/football/arsenal/injury-news/news/arsenal-learn-odegaard-injury-update-as-midfielder-misses-training_605967.html'},
  {date:'2026-09-29', headline:'The Commission publishes its City decision: every charge proven bar one',
   summary:'The Premier League has released the redacted core decision of its independent Commission, and it is no longer a leak: Manchester City were found to have breached the rules on accounts, UEFA break-even and the League’s own profitability limits across nine seasons, and to have failed to cooperate with the investigation in most of the ways alleged. The Commission also said evidence from a number of important City witnesses was false, and that some knew it was untrue. Only Charge 4(B) was not proven. The penalty is still to be decided at a separate hearing, and City have until 2 October to appeal, so the full story is a long way from over.',
   source:'Premier League', url:'https://www.premierleague.com/en/news/4727779/premier-league-statement-manchester-city-fc/'},
  {date:'2026-09-29', headline:'Brazil beat the Socceroos 4-2 in front of a record Suncorp crowd, Gabriel and Bruno in the squad',
   summary:'A record 52,423 packed Suncorp Stadium in Brisbane on Tuesday night to watch Brazil come from behind against Australia, after Alessandro Circati and Connor Metcalfe had given the hosts a first-half lead. Gabriel Magalhães and Bruno Guimarães both travelled with Brazil for the Australian leg of the tour, which began with a 1-1 draw in Townsville on Friday. For Arsenal it is one more fixture on a break that has been good for nobody’s fitness chart; for this site it is simply the closest a Gunner has ever been to home.',
   source:'ESPN', url:'https://www.espn.com/soccer/report/_/gameId/401881965'},
  {date:'2026-09-26', headline:'The scan comes back kind: Havertz’s problem is a strain, not a tear',
   summary:'Two days after being withdrawn against the Netherlands, Havertz has his answer, and it is the one everyone at London Colney was hoping for — imaging shows a muscle strain rather than anything requiring surgery. Nobody at the club is putting a number of weeks on it publicly, and Arteta has more sense than to promise a return date this early, but the arithmetic is kind too: nothing else on the calendar before Leeds visit on the tenth, and more than a fortnight to use it.',
   source:'CBS Sports', url:'https://www.cbssports.com/soccer/news/kai-havertz-arsenal-muscle-strain-germany/'},
  {date:'2026-09-25', headline:'Man City reported guilty on 114 of 115 charges, but nothing is decided yet',
   summary:'David Ornstein of The Athletic reports that the independent commission has found Manchester City guilty on 114 of the 115 financial-rules charges brought in 2023, with one not proven. The Premier League has not published the ruling and no sanction has been set, and City are expected to appeal. Treat it as a report rather than a result: any punishment, and any argument about what it means for the table, is a long way off.',
   source:'Al Jazeera', url:'https://www.aljazeera.com/sports/2026/9/25/man-city-found-guilty-on-almost-all-115-premier-league-charges-report'},
  {date:'2026-09-24', headline:'Havertz’s international window ends early with a hamstring complaint',
   summary:'Germany’s Nations League opener against the Netherlands, the first match of the Jürgen Klopp era, finished 1-1 at a heaving Johan Cruyff Arena — and Havertz didn’t see much of it, withdrawn just past the half-hour with a problem in his hamstring. He has already flown back to north London to be assessed by Arsenal’s own medical staff rather than staying with the squad, which cuts both ways: concerning enough to want him home straight away, reassuring in that there are still sixteen days to go before Leeds visit the Emirates on the tenth of October.',
   source:'Sky Sports', url:'https://www.skysports.com/football/news/13591713/kai-havertz-returning-to-arsenal-to-be-assessed-after-suffering-injury-for-germany-against-netherlands'},
  {date:'2026-09-22', headline:'Arteta ties himself to a decade in the job',
   summary:'The contract talk that has rumbled quietly under the title celebrations all summer is finally settled: Arteta has signed a new long-term deal reported to run into the 2029-30 season, which would take him to a full ten years in the Emirates hot seat since he arrived in December 2019. It comes with a substantial pay rise and, more to the point for anyone who spent August nervous about it, puts an end to any speculation about him walking away after delivering the club’s first title in twenty-two years and a first Champions League final since 2006.',
   source:'Yahoo Sports', url:'https://sports.yahoo.com/articles/mikel-arteta-agrees-long-term-arsenal-121000869.html'},
  {date:'2026-09-21', headline:'Rice withdraws from England’s squad — no explanation offered, and none really needed',
   summary:'Declan Rice is one of five players to pull out of Thomas Tuchel’s squad for the Nations League window, alongside Cole Palmer, Kobbie Mainoo, Marcus Rashford and Tino Livramento. Neither the FA nor Arsenal have said what the issue is, and given the minutes Rice has carried since last season — more than almost anyone else at the club — this reads less like a crisis than a manager quietly finding a fortnight off for a player who badly needed one.',
   source:'Sky Sports', url:'https://www.skysports.com/football/news/13590334/england-latest-cole-palmer-withdraws-from-thomas-tuchels-squad-ahead-of-long-international-break'},
  {date:'2026-09-21', headline:'Three centre-backs, three different clocks, one shared target of 10 October',
   summary:'The international-break update, stripped of the caveats: Ben White is still nursing the groin problem that has dogged him since the season’s opening weeks, Cristhian Mosquera has a genuine shot at being back for Leeds having sat out Brighton as a precaution rather than a fresh injury, and William Saliba remains on his own, slower timeline with the back problem that has kept him out since August. None of it is a confirmed return date. All of it is at least a plan to build the interlull around.',
   source:'AOL', url:'https://www.aol.co.uk/articles/arsenal-injury-ben-white-cristhian-050024000.html'},
  {date:'2026-09-20', headline:'Hincapié left out of Ecuador’s squad — a groin, not a snub',
   summary:'Ecuador have named their squad for a pair of friendlies against South Korea and Japan and Piero Hincapié isn’t in it, ruled out with a groin strain that has left him short of full match fitness. He isn’t alone — Chelsea’s Moisés Caicedo misses the same window for the same reason — so read it as a federation being careful with two Premier League bodies rather than anything specific to Arsenal. A quiet fortnight is arguably the best outcome for a player who only just fought his way back into the back four.',
   source:'Daily Cannon', url:'https://dailycannon.com/2026/09/hincapie-ecuador-injury-absence/'},
  {date:'2026-09-19', headline:'Arteta won’t rule out a Dowman loan — just not yet',
   summary:'Put on the spot about whether Max Dowman could eventually be loaned out, Arteta didn’t shut the door — the club say they will keep reviewing it every six months, while stressing the plan for now is simply to keep developing him inside the first-team bubble rather than send him away from it. Luton Town, managed by Dowman’s former youth coach Jack Wilshere, are already being credited with interest, though nothing can happen before New Year’s Eve, when Dowman turns 17 and becomes old enough to move.',
   source:'Football365', url:'https://www.football365.com/news/arsenal-arteta-max-dowman-transfer-decision'},
  {date:'2026-09-18', headline:'Saliba and Mosquera both out, White a doubt as Arsenal head to the Amex',
   summary:'A perfect four from four goes to Brighton with two centre-backs missing rather than the usual one. William Saliba and Cristhian Mosquera are both unavailable for Saturday, and Ben White is only a doubt on top of that, leaving Arteta thin at the back again. The one genuine bit of good news is Jurrien Timber, back on the pitch for 53 minutes against Sunderland after five months out, though Arteta was clear afterwards that his minutes will keep being managed rather than handed over all at once. Arsenal arrive having conceded once all season; Brighton arrive without a single fit right winger.',
   source:'Yahoo Sports', url:'https://sports.yahoo.com/articles/arsenal-brighton-premier-league-preview-144500099.html'},
  {date:'2026-09-17', headline:'Fourth-round draw sends Arsenal to Fleetwood — at a ground called Highbury',
   summary:'The luck of the pot, delivered as only English football can: League Two’s bottom-tier survivors are the visitors’ reward in the Carabao Cup, at a stadium that has carried the same name as Arsenal’s old home for over a century, pure coincidence and all. Fleetwood got here by knocking out fellow fourth-tier sides Chesterfield and Shrewsbury before beating Championship promotion-chasers Sheffield United in round three, so this is an underdog with actual scalps rather than a gentle draw. The tie is pencilled in for the week commencing 26 October, the first competitive meeting between the two clubs.',
   source:'Sky Sports', url:'https://www.skysports.com/football/news/11938/13588651/carabao-cup-fourth-round-draw-liverpool-to-host-chelsea-as-arsenal-drawn-away-to-league-two-fleetwood'},
  {date:'2026-09-15', headline:'Max Dowman becomes Arsenal’s youngest-ever starter — and scores twice to sink Ipswich',
   summary:'Sixteen years and 258 days old, handed a start in a heavily rotated side at Portman Road, and the response was two goals in a 4-2 Carabao Cup win — one either side of strikes from Madueke and Merino, with Ipswich pulling two back late through Mehmeti and Akpom that never threatened the result. It made him the youngest player ever to start a match for this club. Arteta’s read on him afterwards was the tell: “A tiny smile, that’s what you get with him... he doesn’t make a big fuss of it.” Arsenal are through to round four.',
   source:'Sky Sports', url:'https://www.skysports.com/football/news/11095/13582699/ipswich-2-4-arsenal-max-dowman-shines-with-two-goals-as-gunners-ease-into-carabao-cup-fourth-round'},
  {date:'2026-09-14', headline:'Timber gets through Sunderland unscathed — and looks set for his first start of the season',
   summary:'Buried under two separate fitness worries was the update this site has been waiting a month for. Ben White didn’t make it to half-time at the Stadium of Light, withdrawn with what looked like a groin complaint, and William Saliba is now out of Monday’s Carabao Cup trip to Portman Road with a back problem. But Jurrien Timber came through his second-half cameo against Sunderland with nothing wrong, and Arteta all but confirmed he’ll start against Ipswich — the actual return, not another round of “closing in.” Cristhian Mosquera remains a doubt of his own.',
   source:'Sports Mole', url:'https://www.sportsmole.co.uk/football/arsenal/league-cup/team-news/ipswich-vs-arsenal-injury-suspension-list-predicted-xis_605060.html'},
  {date:'2026-09-13', headline:'Arsenal want Pro Ref to explain the Sunderland penalty, VAR and all',
   summary:'David Raya saved it, so the three points were never really at risk, but the club aren’t letting the decision go quietly. Referee John Brooks gave Sunderland a spot-kick for a challenge by Ezri Konsa on Dan Ballard that looked soft from every angle shown, VAR checked it and waved it through regardless, and Arsenal have now asked Pro Ref — the body that oversees Premier League officials — for an explanation of both calls. Arteta’s verdict from the press conference, delivered once he’d had a day to cool off, was that it simply shouldn’t happen at this level.',
   source:'ESPN', url:'https://www.espn.com/soccer/story/_/id/49939662/arsenal-contact-pro-ref-sunderland-penalty-incident-source'},
  {date:'2026-09-13', headline:'Twenty years of the Emirates, told in a handful of numbers',
   summary:'Two decades since the move from Highbury, and the club marked it with a stat sheet rather than a ceremony, which feels about right for a ground built on financial discipline rather than sentiment. The shirt-and-stadium sponsorship is still the longest-running of its kind in the Premier League. Gilberto Silva scored the first competitive goal there, wearing No. 19. Eighteen hat-tricks have gone in since and not one of them belonged to the visitors, and the heaviest scoreline anyone has managed in a single game there is still ten goals, set the afternoon Arsenal put seven past Newcastle in 2012.',
   source:'Arsenal.com', url:'https://arsenal.com/news/emirates-at-20-the-stats-breakdown-aiV0A9T0lVxm'},
  {date:'2026-09-11', headline:'Arsenal get a clean bill ahead of Sunderland: White in, Timber close, Mosquera not far behind',
   summary:'Arteta’s pre-Sunderland briefing was about as good as these things get this early in the season. Ben White has trained through his knock and travels to the Stadium of Light. Jurrien Timber, out since the spring, has been working with the group for several days and is now a genuine selection option rather than a hopeful one. Cristhian Mosquera, sidelined since the Villa game, is being talked about in terms of this weekend or the next rather than in the abstract. Five games unbeaten and the treatment room is finally starting to look normal.',
   source:'Yahoo Sports', url:'https://ca.sports.yahoo.com/news/arteta-provides-injury-updates-arsenal-085000743.html'},
  {date:'2026-09-10', headline:'Festive fixtures land: Palace moves to a Sunday, Fulham and Brentford both shift kick-off times',
   summary:'The Premier League’s Boxing Day round is never actually all on Boxing Day, and this year Arsenal’s trip to Selhurst Park is the one that moves — Crystal Palace away is now Sunday 27 December, 7pm, live on Sky. The following Fulham trip stays on the 30th but shunts back half an hour to 7.30pm, also live. Brentford at home loses a day off the calendar too, sliding from the 6th to Tuesday 5 January, again 7.30pm and again on Sky. Only the Ipswich game on New Year’s weekend survives untouched — 3pm on the 2nd, and still nowhere on UK television. Book accordingly.',
   source:'Arsenal.com', url:'https://www.arsenal.com/news/premier-league-festive-fixture-details-confirmed-atjUt4t54LGl'},
  {date:'2026-09-09', headline:'Arsenal open the Champions League with an away win at Napoli',
   summary:'First points on the board in Europe, and it came the hard way — away, at a ground that does not do quiet nights. Ødegaard settled it with fifteen minutes left, low into the corner off a Tzolis assist. One down, seven to go.',
   source:'VAVEL', url:'https://www.vavel.com/en-us/soccer/2026/09/09/1270590-napoli-vs-arsenal-live-score-uefa-champions-league.html'},
  {date:'2026-09-08', headline:'Rice, Saliba and Gabriel picked for Ballon d’Or shortlist, Raya up for the Yashin Trophy',
   summary:'Three names on the 30-man shortlist for the game’s biggest individual prize, which tells you something about where this squad has got to even if none of them will be troubling the podium. Declan Rice and William Saliba return to the list, Gabriel makes it for the first time, and David Raya’s season earns him a nomination for the Yashin Trophy instead, the goalkeeper-specific award. Arteta’s own body of work has him shortlisted for Men’s Coach of the Year alongside a small group that includes Unai Emery. The ceremony is in London on 26 October, which for once means nobody has to stay up for it.',
   source:'Yahoo Sports', url:'https://sports.yahoo.com/articles/arsenal-rack-nominations-ballon-d-120500413.html'},
  {date:'2026-09-08', headline:'Arsenal sign Crystal Palace academy striker Mylo Bernard',
   summary:'The ins-and-outs are not only senior-squad business. Palace’s leading Under-18 scorer this season joins as a scholar, with a pro contract already lined up for when he turns seventeen — eight years at Palace, gone in one announcement.',
   source:'Arsenal.com', url:'https://www.arsenal.com/news/mylo-bernard-joins-arsenal-a6HBo1d0UJCP'},
  {date:'2026-09-05', headline:'Arteta: Mosquera absence precautionary, Timber closing in on a return',
   summary:'Arteta downplayed Mosquera sitting out the Chelsea game as precaution rather than a fresh knock, and gave the clearest signal yet that Timber’s long lay-off is nearly over — “in a really good condition,” with a call on his involvement coming after Saturday’s session.',
   source:'Daily Cannon', url:'https://dailycannon.com/2026/09/arteta-alonso-arsenal-chelsea-injury-updates/'}
];
